theme: jekyll-theme-cayman


title: "Variational Stochastic Gradient Descent for Deep Neural Networks"
description: "Code repository of the paper Variational Stochastic Gradient Descent for Deep Neural Networks"

