name: vsgd
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
  - huggingface
dependencies:
  - python=3.10.4
  - numpy
  - scipy
  - matplotlib
  - wandb
  - tqdm
  - imageio
  - pip
  - wheel
  - pytorch=1.12.1
  - torchvision=0.13.1
  - cudatoolkit=11.3
  - torchmetrics
  - transformers
  - pip:
      - hydra-core==1.3
      - torch-fidelity==0.3.0
      - black

