---
_target_: model.classifier.ClassifierWrapper
backbone:
  _target_: transformers.ResNetForImageClassification
  config:
    _target_: transformers.ResNetConfig
    num_channels: 3 
    embedding_size: 64  # Dimensionality (hidden size) for the embedding layer.
    hidden_sizes: # (List[int], optional, defaults to [256, 512, 1024, 2048]) — Dimensionality (hidden size) at each stage.
      - 64
      - 128
      - 256
      - 512
    depths: # (List[int], optional, defaults to [3, 4, 6, 3]) — Depth (number of layers) for each stage.
      - 2 
      - 2 
      - 2 
      - 2
    layer_type: "basic" # (str, optional, defaults to "bottleneck") — The layer to use, it can be either "basic" (used for smaller models, like resnet-18 or resnet-34) or "bottleneck" (used for larger models like resnet-50 and above).
    hidden_act: "relu" # (str, optional, defaults to "relu") — The non-linear activation function in each block. If string, "gelu", "relu", "selu" and "gelu_new" are supported.
    downsample_in_first_stage: False # (bool, optional, defaults to False) — If True, the first stage will downsample the inputs using a stride of 2.
    downsample_in_bottleneck: False # (bool, optional, defaults to False) — If True, the first conv 1x1 in ResNetBottleNeckLayer will downsample the inputs using a stride of 2.
    num_labels: ${dataset.num_classes}

name: resnet
# see https://huggingface.co/docs/transformers/main/en/model_doc/resnet#transformers.ResNetConfig for more details